FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Back/Entrypoint/WebApi/WebApi.csproj", "Back/Entrypoint/WebApi/"]
RUN dotnet restore "Back/Entrypoint/WebApi/WebApi.csproj"
COPY . .
WORKDIR "/src/Back/Entrypoint/WebApi"
RUN dotnet build "WebApi.csproj" --configuration Release --no-restore

FROM build AS publish
RUN dotnet publish "WebApi.csproj" --configuration Release --no-restore --output /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApi.dll"]
